#!/bin/bash

source /root/venv/bin/activate

HOSTVPN=https://vpn.kalunga.com.br
BASE32_TOKEN=FWXUXRNPFDG5XLCUSTJ5WTVNMTPM4X3PGCT4ZA6P4VQPPKETPSZGZJMQLWTEJUQEYH3QPZVGF7GE7IOOEJZVUPSWH6S4JTTRBUAIKA7SWMMNIHEMTER5I73O2DKLW6X7W5XEHO42W4YDGWMQOUH4722KE7V7EMIZZRQAUVHUGRDTN6XBXVKCN7Y6ZLWWFEPYGBHSKF7JOFW4W
TOKEN=`oathtool --base32 --totp $BASE32_TOKEN`
USER="daniloka"
PASSWORD="kalunga07"
SEQUENCE="\n${USER}\n${PASSWORD}\n${TOKEN}"

echo -e $SEQUENCE | openconnect $HOSTVPN --config='/home/danilo/GitHub/dvovalle/vpn/configvpn.conf'

exit 0
